#!/bin/bash

for tag in jre8h jre8 jdk8 jre11h jre11 jdk11 jdk11-jmods jdk8-mvn jdk11-mvn jdk11-mvn-jmods ; do
  docker push $DOCKER_REPO:$tag
done

docker tag $DOCKER_REPO:jre11h $DOCKER_REPO:jreh
docker push $DOCKER_REPO:jreh
docker tag $DOCKER_REPO:jre11 $DOCKER_REPO:jre
docker push $DOCKER_REPO:jre
docker tag $DOCKER_REPO:jdk11 $DOCKER_REPO:jdk
docker push $DOCKER_REPO:jdk

docker tag $DOCKER_REPO:jdk11 $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest

docker tag $DOCKER_REPO:jdk11-mvn $DOCKER_REPO:jdk-mvn
docker push $DOCKER_REPO:jdk-mvn
